site_name: Titus
repo_url: https://github.com/Netflix/titus
strict: True

pages:
- 'Overview': overview.md
- 'Building the Code': build.md
- 'Deployment':
  - 'Prereqs': install/prereqs.md
  - 'Amazon Prereqs': install/prereqs-amazon.md
  - 'Master and Gateway': install/master.md
  - 'Agent': install/agent.md
- 'Testing':
  - 'Basic batch task': test/batch.md
- 'FAQ': faq.md
theme: material
