site_name: Titus
theme_dir: docs/theme
repo_url: https://github.com/Netflix/titus
strict: True

pages:
- 'Introduction' : index.md
- 'Building the Code': build.md
- 'Deployment Overview': install/index.md
  - 'Prereqs': install/prereqs.md
  - 'Scheduler and Gateway': install/master.md
  - 'Agent': install/agent.md
- 'FAQ': faq.md
- License: 'license.md'
theme: readthedocs
markdown_extensions:
- admonition
- toc:
    permalink: True    
