site_name: Titus
repo_url: https://github.com/Netflix/titus
strict: True

pages:
- 'Introduction': index.md
- 'Building the Code': build.md
- 'Deployment':
  - 'Prereqs': install/prereqs.md
  - 'Scheduler and Gateway': install/master.md
  - 'Agent': install/agent.md
- 'Testing':
  - 'Basic batch task': test/batch.md
- 'FAQ': faq.md
theme: readthedocs
